// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tfi.Data.Context;

#nullable disable

namespace Tfi.Data.Migrations
{
    [DbContext(typeof(ARContext))]
    [Migration("20251116234559_Cuarto-Modelo")]
    partial class CuartoModelo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ResourceTask", b =>
                {
                    b.Property<int>("ResourcesId")
                        .HasColumnType("int");

                    b.Property<int>("TasksId")
                        .HasColumnType("int");

                    b.HasKey("ResourcesId", "TasksId");

                    b.HasIndex("TasksId");

                    b.ToTable("ResourceTask");
                });

            modelBuilder.Entity("Tfi.Domain.Entities.ChangeHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Budget")
                        .HasColumnType("float")
                        .HasColumnName("presupuesto");

                    b.Property<DateTime>("ChangeDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("fechaCambio");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("FunctionsSnapshot")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("oldFunctions");

                    b.Property<int>("ProyectId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("motivoCambio");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ProyectId");

                    b.ToTable("historial_cambios", (string)null);
                });

            modelBuilder.Entity("Tfi.Domain.Entities.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Direction")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("direccionCliente");

                    b.Property<int>("Dni")
                        .HasColumnType("int")
                        .HasColumnName("dni");

                    b.Property<string>("Mail")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("mailCliente");

                    b.Property<string>("Name")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("nombreCliente");

                    b.Property<string>("Phone")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("telefonoCliente");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("clientes", (string)null);
                });

            modelBuilder.Entity("Tfi.Domain.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Direction")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("direccionEmpleado");

                    b.Property<int>("Dni")
                        .HasColumnType("int")
                        .HasColumnName("dniEmpleado");

                    b.Property<string>("LastName")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("apellidoEmpleado");

                    b.Property<string>("Mail")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("mailEmpleado");

                    b.Property<string>("Name")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("nombreEmpleado");

                    b.Property<string>("Phone")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("telefonoEmpleado");

                    b.Property<int>("RolEmpleado")
                        .HasColumnType("int")
                        .HasColumnName("rolEmpleado");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("empleados", (string)null);
                });

            modelBuilder.Entity("Tfi.Domain.Entities.Function", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("descripcionFuncionalidad");

                    b.Property<string>("Name")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("nombreFuncionalidad");

                    b.Property<int>("ProyectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProyectId");

                    b.ToTable("funcionalidades", (string)null);
                });

            modelBuilder.Entity("Tfi.Domain.Entities.Incidence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("descripcionIncidencia");

                    b.Property<int>("ProyectId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RegisterDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("fechaIncidencia");

                    b.Property<string>("Type")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("tipoIncidencia");

                    b.HasKey("Id");

                    b.HasIndex("ProyectId");

                    b.ToTable("incidencias", (string)null);
                });

            modelBuilder.Entity("Tfi.Domain.Entities.Proyect", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Budget")
                        .HasColumnType("float")
                        .HasColumnName("presupuestoProyecto");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateEnd")
                        .HasColumnType("datetime2")
                        .HasColumnName("fechaFinProyecto");

                    b.Property<DateTime>("DateInitial")
                        .HasColumnType("datetime2")
                        .HasColumnName("fechaInicioPreyecto");

                    b.Property<string>("Description")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("descripcionProyecto");

                    b.Property<string>("Name")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("nombreProyecto");

                    b.Property<int>("Priority")
                        .HasColumnType("int")
                        .HasColumnName("prioridadProyecto");

                    b.Property<int>("State")
                        .HasColumnType("int")
                        .HasColumnName("estadoProyecto");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("tipoProyecto");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("TeamId");

                    b.ToTable("proyectos", (string)null);
                });

            modelBuilder.Entity("Tfi.Domain.Entities.Resource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("descripcionRecurso");

                    b.HasKey("Id");

                    b.ToTable("recursos", (string)null);
                });

            modelBuilder.Entity("Tfi.Domain.Entities.Task", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("descripcionTarea");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("fechaFinTarea");

                    b.Property<int>("FunctionId")
                        .HasColumnType("int");

                    b.Property<int>("ImplementationStatus")
                        .HasColumnType("int")
                        .HasColumnName("estadoImplementación");

                    b.Property<DateTime>("InitialDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("fechaInicioTarea");

                    b.Property<string>("Name")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("nombreTarea");

                    b.Property<int>("Priority")
                        .HasColumnType("int")
                        .HasColumnName("prioridadTarea");

                    b.Property<int>("State")
                        .HasColumnType("int")
                        .HasColumnName("estadoTarea");

                    b.HasKey("Id");

                    b.HasIndex("FunctionId");

                    b.ToTable("tareas", (string)null);
                });

            modelBuilder.Entity("Tfi.Domain.Entities.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Number")
                        .HasColumnType("int")
                        .HasColumnName("numeroEquipo");

                    b.HasKey("Id");

                    b.ToTable("equipos", (string)null);
                });

            modelBuilder.Entity("Tfi.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .HasMaxLength(65)
                        .HasColumnType("nvarchar(65)")
                        .HasColumnName("contraseniaUsuario");

                    b.Property<string>("UserName")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("nombreUsuario");

                    b.HasKey("Id");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("ResourceTask", b =>
                {
                    b.HasOne("Tfi.Domain.Entities.Resource", null)
                        .WithMany()
                        .HasForeignKey("ResourcesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tfi.Domain.Entities.Task", null)
                        .WithMany()
                        .HasForeignKey("TasksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tfi.Domain.Entities.ChangeHistory", b =>
                {
                    b.HasOne("Tfi.Domain.Entities.Employee", "Employee")
                        .WithMany("ChangesHistory")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tfi.Domain.Entities.Proyect", "Proyect")
                        .WithMany("ChangesHistory")
                        .HasForeignKey("ProyectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Proyect");
                });

            modelBuilder.Entity("Tfi.Domain.Entities.Employee", b =>
                {
                    b.HasOne("Tfi.Domain.Entities.Team", "Team")
                        .WithMany("Employees")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tfi.Domain.Entities.User", "User")
                        .WithOne("Employee")
                        .HasForeignKey("Tfi.Domain.Entities.Employee", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Tfi.Domain.Entities.Function", b =>
                {
                    b.HasOne("Tfi.Domain.Entities.Proyect", "Proyect")
                        .WithMany("Functions")
                        .HasForeignKey("ProyectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proyect");
                });

            modelBuilder.Entity("Tfi.Domain.Entities.Incidence", b =>
                {
                    b.HasOne("Tfi.Domain.Entities.Proyect", "Proyect")
                        .WithMany("Incidences")
                        .HasForeignKey("ProyectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proyect");
                });

            modelBuilder.Entity("Tfi.Domain.Entities.Proyect", b =>
                {
                    b.HasOne("Tfi.Domain.Entities.Client", "Client")
                        .WithMany("Proyects")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tfi.Domain.Entities.Team", "Team")
                        .WithMany("Proyects")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Tfi.Domain.Entities.Task", b =>
                {
                    b.HasOne("Tfi.Domain.Entities.Function", "Function")
                        .WithMany("Tasks")
                        .HasForeignKey("FunctionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Function");
                });

            modelBuilder.Entity("Tfi.Domain.Entities.Client", b =>
                {
                    b.Navigation("Proyects");
                });

            modelBuilder.Entity("Tfi.Domain.Entities.Employee", b =>
                {
                    b.Navigation("ChangesHistory");
                });

            modelBuilder.Entity("Tfi.Domain.Entities.Function", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("Tfi.Domain.Entities.Proyect", b =>
                {
                    b.Navigation("ChangesHistory");

                    b.Navigation("Functions");

                    b.Navigation("Incidences");
                });

            modelBuilder.Entity("Tfi.Domain.Entities.Team", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("Proyects");
                });

            modelBuilder.Entity("Tfi.Domain.Entities.User", b =>
                {
                    b.Navigation("Employee");
                });
#pragma warning restore 612, 618
        }
    }
}
